# Generated by Django 4.1.1 on 2022-10-12 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='like',
        ),
    ]
